feat: add convenience fileURLToPath() alias as filename()
mcollina/desm pull request #3
Opened 2021-12-22 17:26 UTC by galvez

It is a common occurrence to have to import both `desm` and `fileURLToPath` since `fs` methods don't work with URLs.

2021-12-23 17:36 UTC, mcollina requested changes
Can you please add a unit test?

2022-05-26 21:16 UTC, nexdrew commented
Now that #4 has been merged and included in the 1.3.0 release, I think we can safely close this PR.

2022-05-26 21:18 UTC, galvez commented
Indeed — I completely forgot about this one. Thanks @nexdrew

2022-05-26 21:18 UTC, closed without merging

2022-05-26 21:24 UTC, nexdrew commented
@galvez No worries, thanks for getting the ball rolling here!